import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import DonateBox from "../components/DonateBox"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bitcoin Fundraising</title>
        <meta name="description" content="Generated by create next app" />
        <script async src="lib/strike.min.js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Donate to, <a  rel="noreferrer" target="_blank" href="https://thenirvana.life/">The Nirvana Life!</a>
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>Nirvana (Sanskrit: निर्वाण, Nirvāna; Pali: निब्बान, Nibbāna;) is the state of being free from both suffering and the cycle of rebirth. &quot;Nibbāna&quot; is a Pāli word that means &quot;blowing out&quot; — that is, blowing out the fires of greed, hatred, and delusion.</code>
        </p>
        <div className={styles.grid}>

          <DonateBox />
          <span className={styles.card}>
          <h2 className="font-mono"> Goal &rarr;</h2>
          <div className="shadow stats stats-vertical">
          <div className="stat">
            <div className="stat-figure text-primary">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-8 h-8 stroke-current"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path></svg>
            </div>
            <div className="stat-title">Target</div>
            <div className="stat-value text-primary">$89,400</div>
            <div className="stat-desc">0% fees with strike</div>
          </div>

          <div className="stat">
            <div className="stat-figure text-secondary">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-8 h-8 stroke-current"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
            </div>
            <div className="stat-title">Funds Raised</div>
            <div className="stat-value text-secondary">$9,400</div>
            <div className="stat-desc">By 500 Awesome donors</div>
          </div>
        </div>
          </span>

          <span className={styles.card}  >
            <h2 className="font-mono">Recent Donors &rarr;</h2>
            <div className="bg-white rounded-lg shadow w-full">
              <ul className="divide-y divide-gray-100">
                <li className="p-3 hover:bg-blue-600 hover:text-blue-200">
                    <div className="badge badge-secondary">$5</div> by Anonymous
                </li>
                <li className="p-3 hover:bg-blue-600 hover:text-blue-200">
                    <div className="badge badge-secondary">$5</div> All the best
                </li>
                <li className="p-3 hover:bg-blue-600 hover:text-blue-200">
                    <div className="badge badge-secondary">$5</div> Thanks for the script - Steve
                </li>
              </ul>
            </div>
          </span>

          <span className={styles.card }>
            <div className="card bg-base-100  bg-base-100 shadow-xl">
              <figure className="px-10 pt-10">
                <Image width={200} height={200} src="/images/bitcoin-btc-logo-full.svg" alt="Bitcoin" className="rounded-xl object-contain	" />
              </figure>
              <div className="card-body items-center text-center">
                <p>“#Bitcoin is the end of human suffering.” - <div className="stat-desc">Buddha on #Bitcoin</div></p>
              </div>
            </div>
          </span>
        </div>
      </main>
      <div className="bg-gradient-to-l from-green-300 via-blue-500 to-purple-600 rounded-md grid grid-cols-1 md:grid-cols-3 justify-center items-center p-8 shadow text-gray-50 mx-4 md:mx-20 my-6">
        <div>
          <h1 className="font-semibold md:text-2xl text-center md:text-left my-2">Want to create your own Fundraising Page ?</h1>
          <p className="text-gray-100 text-sm md:text-base font-light">You can   <a rel="noreferrer" target="_blank" href="https://github.com/rahulbile/fundraising">Fork </a> the setup from github repo and get started with your specific use case.</p>
        </div>
        <div className="mx-auto">
          <div className="flex flex-row items-center space-x-2 my-4 justify-start">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-50 mt-1">
              <path d="M10.2426 16.3137L6 12.071L7.41421 10.6568L10.2426 13.4853L15.8995 7.8284L17.3137 9.24262L10.2426 16.3137Z" fill="currentColor" />
              <path fillRule="evenodd" clipRule="evenodd" d="M1 12C1 5.92487 5.92487 1 12 1C18.0751 1 23 5.92487 23 12C23 18.0751 18.0751 23 12 23C5.92487 23 1 18.0751 1 12ZM12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21Z" fill="currentColor" />
            </svg>
            <p className="text-white text-sm"> <a
            rel="noreferrer" target="_blank" href="https://invite.strike.me/R9ASCS">Download Strike</a></p>
          </div>
          <div className="flex flex-row items-center space-x-2 my-4 justify-start">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-50 mt-1">
              <path d="M10.2426 16.3137L6 12.071L7.41421 10.6568L10.2426 13.4853L15.8995 7.8284L17.3137 9.24262L10.2426 16.3137Z" fill="currentColor" />
              <path fillRule="evenodd" clipRule="evenodd" d="M1 12C1 5.92487 5.92487 1 12 1C18.0751 1 23 5.92487 23 12C23 18.0751 18.0751 23 12 23C5.92487 23 1 18.0751 1 12ZM12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21Z" fill="currentColor" />
            </svg>
            <p className="text-white text-sm">Create Account</p>
          </div>
          <div className="flex flex-row items-center space-x-2 my-4 justify-start">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-50 mt-1">
              <path d="M10.2426 16.3137L6 12.071L7.41421 10.6568L10.2426 13.4853L15.8995 7.8284L17.3137 9.24262L10.2426 16.3137Z" fill="currentColor" />
              <path fillRule="evenodd" clipRule="evenodd" d="M1 12C1 5.92487 5.92487 1 12 1C18.0751 1 23 5.92487 23 12C23 18.0751 18.0751 23 12 23C5.92487 23 1 18.0751 1 12ZM12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21Z" fill="currentColor" />
            </svg>
            <p className="text-white text-sm">Get API Key</p>
          </div>
          <div className="flex flex-row items-center space-x-2 my-4 justify-start">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-50 mt-1">
              <path d="M10.2426 16.3137L6 12.071L7.41421 10.6568L10.2426 13.4853L15.8995 7.8284L17.3137 9.24262L10.2426 16.3137Z" fill="currentColor" />
              <path fillRule="evenodd" clipRule="evenodd" d="M1 12C1 5.92487 5.92487 1 12 1C18.0751 1 23 5.92487 23 12C23 18.0751 18.0751 23 12 23C5.92487 23 1 18.0751 1 12ZM12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21Z" fill="currentColor" />
            </svg>
            <p className="text-white text-sm">Start Fundriasing</p>
          </div>
        </div>
        <div className="mx-auto">
          <div className="flex flex-row items-center space-x-2 my-4 justify-start">
            <a target="_blank" rel="noreferrer" href="https://invite.strike.me/R9ASCS"><button className="px-8 py-4 bg-slate-900 text-white font-semibold rounded-md">Download Strike</button></a>
          </div>
          <div className="flex flex-row items-center space-x-2 my-4 justify-start">
          <a target="_blank"rel="noreferrer"  href="https://github.com/rahulbile/fundraising"><button className="px-8 py-4 bg-green-600 text-white font-semibold rounded-md">Fork Project<svg className="inline h-7 w-7 text-black"  width="24" height="24" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" fill="none" strokeLinecap="round" strokeLinejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <path d="M9 19c-4.286 1.35-4.286-2.55-6-3m12 5v-3.5c0-1 .099-1.405-.5-2 2.791-.3 5.5-1.366 5.5-6.04a4.567 4.567 0 0 0 -1.333 -3.21 4.192 4.192 0 00-.08-3.227s-1.05-.3-3.476 1.267a12.334 12.334 0 0 0 -6.222 0C6.462 2.723 5.413 3.023 5.413 3.023a4.192 4.192 0 0 0 -.08 3.227A4.566 4.566 0 004 9.486c0 4.64 2.709 5.68 5.5 6.014-.591.589-.56 1.183-.5 2V21" /></svg> </button></a>
          </div>
        </div>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://twitter.com/rahulbile"
          target="_blank"
          rel="noreferrer"
        >
          Created with ♥️ by Rahul Bile
        </a>
      </footer>
      </div>
  )
}
